// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyC2btJkqddjHfj0Awp3rrxrXVssvzxAeBU',
  //   appId: '1:913483360853:android:3bff9e898361b78d8882dc',
  //   messagingSenderId: '913483360853',
  //   projectId: 'petition-36ee7',
  //   authDomain: 'petition-36ee7.firebaseapp.com',
  //   databaseURL:
  //   'https://petition-36ee7-default-rtdb.firebaseio.com',
  //   storageBucket: 'petition-36ee7.appspot.com',
  //   measurementId: 'G-JN95N1JV2E',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkHn6p-nr4isFicjGPBT_Oh05Vsh6KDMw',
    appId: '1:988287623865:android:babd74456eb0030c687168',
    messagingSenderId: '988287623865',
    projectId: 'sga-2609',
    // databaseURL:
    // 'https://abody-c8160.firebaseio.com',
    // storageBucket: 'abody-c8160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9KxKrhpQC7C4EqeP67zEIUTPRbjKfEMg',
    appId: '1:988287623865:ios:6bb9896087b88b5b687168',
    messagingSenderId: '988287623865',
    projectId: 'sga-2609',
    // databaseURL: 'https://abody-c8160.firebaseio.com',
    // storageBucket: 'abody-c8160.appspot.com',
    androidClientId:
        '988287623865-2m7kmnfkfdp3iqt4ldqj6midtc5v05vf.apps.googleusercontent.com',
    iosClientId:
        '988287623865-s9r84akogi8a8kmkrq76ejoa1klf7qlt.apps.googleusercontent.com',
    iosBundleId: 'ai.sga.demo',
  );

// static const FirebaseOptions macos = FirebaseOptions(
//   apiKey: 'AIzaSyC2btJkqddjHfj0Awp3rrxrXVssvzxAeBU',
//   appId: '1:913483360853:android:3bff9e898361b78d8882dc',
//   messagingSenderId: '913483360853',
//   projectId: 'petition-36ee7',
//   databaseURL:
//   'https://petition-36ee7-default-rtdb.firebaseio.com',
//   storageBucket: 'petition-36ee7.appspot.com',
//   androidClientId:
//   '406099696497-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
//   iosClientId:
//   '406099696497-1ugbsqv8nkfn788ep0k233e750aupb7u.apps.googleusercontent.com',
//   iosBundleId: 'io.flutter.plugins.firebaseDatabaseExample',
// );
}
